# https://identity.foundation/didcomm-messaging/spec/#trust-ping-protocol-20

### Message (Trust-Ping): response requested : true
POST {{baseUrl}}{{didcommPath}}
Content-Type: application/json

{
  "type": "https://didcomm.org/trust-ping/2.0/ping",
  "id": "123456789",
  "from": "{{userPeerDid}}",
  "to": [
        "{{{{mediatorPeerDid}}}}"
    ],
  "body": {
      "response_requested": true
  }
}

### Message (Trust-Ping): response requested : false
POST {{baseUrl}}{{didcommPath}}
Content-Type: application/json

{
  "type": "https://didcomm.org/trust-ping/2.0/ping",
  "id": "123456789",
  "from": "{{userPeerDid}}",
  "to": [
        "{{mediatorPeerDid}}"
    ],
  "body": {
      "response_requested": false
  }
}