env: DEV # DEV, PROD
logLevel: "info" # info, debug, warning, error
label: My Mediator
port: 8081
url: "http://localhost:8081"
tokenExpiration: 500000
didcomm:
  resolverUrl: "http://localhost:8080"
  messageEncrypted: false

# database
db:
  inMemory: false
  host: "localhost"
  port: 9042
  user: "cassandra"
  password: "f0U5AoZtVk"
  keyspace: "didcomm_space"
  dbName: "cassandra"

# config for cloudEventProdvider
messaging:
  protocol: "nats"
  nats:
    url: "nats://localhost:4222"
    topic: "/message/receive"
    queueGroup: logger # optional
    timeoutInSec: 10 # optional

  http:
    url: "http://localhost:1111" # URL to send cloud event
    port: 1111 # port to send cloud event
    path: "xyz" # Path to receive cloud event