version: "3"

networks:
  test:
    name: test_network
    external:
      true
  
services: 
  didcomconnectorBeta:
    image: node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/common-services/didcomm-connector:refactoring
    container_name: dccBeta
    depends_on:
        uni-resolverBeta:
           condition: service_healthy
        cassandraBeta:
           condition: service_healthy
  
    ports:
      - 9093:8080
    environment:
        - DIDCOMMCONNECTOR_DIDCOMM_RESOLVERURL=http://uni-resolverBeta:8081
        - DIDCOMMCONNECTOR_CLOUDFORWARDING_NATS_URL=nats://natsBeta:4222
        - DIDCOMMCONNECTOR_DATBASE_HOST=cassandraBeta
        - DIDCOMMCONNECTOR_DATBASE_KEYSPACE=tenant_space
        - DIDCOMMCONNECTOR_DATBASE_DBNAME=dcc
        - DIDCOMMCONNECTOR_DATBASE_PORT=9042
        - DIDCOMMCONNECTOR_CLOUDFORWARDING_NATS_TOPIC=connector
        - DIDCOMMCONNECTOR_URL=http://localhost:9092
        - DIDCOMMCONNECTOR_CLOUDFORWARDING_PROTOCOL=nats
    networks: 
      - test


  natsBeta:
    image: nats:latest
    container_name: natsBeta
    ports:
      - "4224:4222"
    networks: 
      - test

  uni-resolverBeta:
    image: universalresolver/uni-resolver-web:latest
    container_name: uni-resolverBeta
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --fail http://uni-resolver:8080/1.0/testIdentifers || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
       uniresolver_web_driver_url_did_jwk:  http://did-jwk-driver:8080
       uniresolver_web_driver_url_did_peer: http://uni-resolver-driver-did-uport:8081
       uniresolver_web_driver_url_did_web:  http://did-jwk-driver:8080
    networks: 
      - test

  uni-resolver-driver-did-uport:
    image: uport/uni-resolver-driver-did-uport:5.0.0
    ports:
      - "8083:8081"
    networks: 
      - test
  did-jwk-driver:
    image: transmute/restricted-resolver:latest
    ports:
      - "8134:8080"
    networks: 
      - test

  cassandraBeta:
    image: cassandra:4.1
    container_name: cassandra_dbBeta
    ports:
      - 7001:7000
      - 9044:9042
    networks: 
      - test
    healthcheck:
      test: cqlsh 
      interval: 30s
      timeout: 120s
      retries: 5