version: "3"

networks:
  test:
   driver: bridge
  resolver:
    driver: bridge

name: didcomm-connector

services:
  dcc:
    build:
      dockerfile: "deployment/docker/Dockerfile"
      context: "../../."
#    image: "didcommconnector:latest"
    networks:
        - test
    depends_on:
      - cassandra
      - uni-resolver-driver-did-uport
    ports:
      - 9090:9090
    environment:
      #      DIDCOMM SETUP
      DIDCOMMCONNECTOR_ENV: "DEV"
      DIDCOMMCONNECTOR_LOGLEVEL: "info"
      DIDCOMMCONNECTOR_PORT: 9090
      DIDCOMMCONNECTOR_URL: "http://localhost:9090"
      DIDCOMMCONNECTOR_LABEL: "My Mediator"
      DIDCOMMCONNECTOR_TOKENEXPIRATION: 500000
      DIDCOMMCONNECTOR_DIDCOMM_RESOLVERURL: "http://host.docker.internal:8080"
      DIDCOMMCONNECTOR_DIDCOMM_ISMESSAGEENCRYPTED: false
      #      DATABASE SETUP
      DIDCOMMCONNECTOR_DATBASE_INMEMORY: false
      DIDCOMMCONNECTOR_DATBASE_HOST: "cassandra:9042"
      DIDCOMMCONNECTOR_DATBASE_PORT: 9042
      DIDCOMMCONNECTOR_DATBASE_USER: "cassandra"
      DIDCOMMCONNECTOR_DATBASE_PASSWORD: "cassandra"
      DIDCOMMCONNECTOR_DATBASE_KEYSPACE: "dcc"
      DIDCOMMCONNECTOR_DATBASE_DBNAME: "cassandra"
      #      CLOUDEVENT PROVIDER SETUP
      DIDCOMMCONNECTOR_CLOUDFORWARDING_PROTOCOL: "nats"
      DIDCOMMCONNECTOR_CLOUDFORWARDING_NATS_URL: "nats://nats:4222"
      DIDCOMMCONNECTOR_CLOUDFORWARDING_NATS_TOPIC: "/message/receive"
      DIDCOMMCONNECTOR_CLOUDFORWARDING_NATS_QUEUEGROUP: "logger"
      DIDCOMMCONNECTOR_CLOUDFORWARDING_HTTP_URL: "http://localhost:1111"


  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks: 
      - test

  uni-resolver:
    image: universalresolver/uni-resolver-web:latest
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --fail http://uni-resolver:8080/1.0/testIdentifers || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
       uniresolver_web_driver_url_did_jwk:  http://host.docker.internal:8134
       uniresolver_web_driver_url_did_peer: http://host.docker.internal:8083
       uniresolver_web_driver_url_did_web:  http://host.docker.internal:8134
    networks: 
      - resolver
  uni-resolver-driver-did-uport:
    image: uport/uni-resolver-driver-did-uport:4.3.0
    ports:
      - "8083:8081"
    networks: 
      - test
  did-jwk-driver:
    image: transmute/restricted-resolver:latest
    ports:
      - "8134:8080"
    networks: 
      - test

  cassandra:
    image: cassandra:latest
    restart: always
    ports:
      - "9042:9042"
    networks:
      - test
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 10