apiVersion: v2
name: didcomm-connector
description: The DIDCommConnector can be used as a Mediator and Connection Management Service by parties who want to set up trust with another party.
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: library
    version: 1.1.1
    repository: oci://node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/dev-ops
